# This is a basic workflow to help you get started with Actions

name: CI
run-name:  ${{ github.actor }} - PR Workflow


# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-task-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTIONS: PythonAApp
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Show Git Hub Actions
        run: echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"
      - name: Branch and repository name
        run: echo "Branch ${{ github.ref }} - Repository ${{ github.repository }}"
      - name: Event that triggered workflow
        run: echo "Event - ${{ github.event_name }}"
